loria_web_service_homepage:
    path:     /loria/{name}
    defaults: { _controller: LoriaWebServiceBundle:Default:index }
loria_web_service_genrepage:
    path:     /loria/genre/{id}
    defaults: { _controller: LoriaWebServiceBundle:Genre:index }
